// Copies the Anchor build output (IDL JSON + TS type) into src/idl as TS modules,
// so consumers need no JSON import support. Run after `anchor build`.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, '..', '..', 'target');
const out = join(here, '..', 'src', 'idl');
mkdirSync(out, { recursive: true });

for (const [name, typeName, constName] of [
  ['bucket_vault', 'BucketVault', 'BUCKET_VAULT_IDL'],
  ['mock_swap', 'MockSwap', 'MOCK_SWAP_IDL'],
]) {
  const jsonPath = join(target, 'idl', `${name}.json`);
  const typePath = join(target, 'types', `${name}.ts`);
  if (!existsSync(jsonPath) || !existsSync(typePath)) {
    if (existsSync(join(out, `${name}.ts`))) continue; // keep the committed copy
    throw new Error(`missing ${jsonPath}; run anchor build first`);
  }
  const json = readFileSync(jsonPath, 'utf8');
  const type = readFileSync(typePath, 'utf8');
  writeFileSync(
    join(out, `${name}.ts`),
    `// GENERATED by scripts/sync-idl.mjs from vault/target — do not edit.\n${type}\nexport const ${constName} = ${json.trim()} as unknown as ${typeName};\n`,
  );
  console.log(`synced ${name}`);
}
